#!/bin/bash
set -e  # stop the script on any error (a command exits with a non-zero status)

# For Mac
if [ "Darwin" = ${OS} ]; then
    if ! [ -x "$(command -v greadlink)"  ]; then
        brew install coreutils
    fi
    BIN_PATH=$(greadlink -f "$0")
    ROOT_DIR=$(dirname "$BIN_PATH")
# For Linux
else
    BIN_PATH=$(readlink -f "$0")
    ROOT_DIR=$(dirname "$BIN_PATH")
fi

SMT_PATH="${ROOT_DIR}/smts"
BAZELRC_PATH="${ROOT_DIR}/.bazelrc"


OS=$(uname -s)
ARCH=$(uname -m)

echo "Detected system: ${OS} (${ARCH})"


install_for_linux() {
    echo "[*] Installing dependencies for Linux ..."

    # Ensure apt exists (for Debian/Ubuntu only)
    if ! command -v apt-get &> /dev/null; then
        echo "Error: apt-get not found. This script supports only Debian/Ubuntu-based systems."
        exit 1
    fi

    # Update package index
    sudo apt-get update -y

    # Install OpenJDK 11
    echo "[*] Installing OpenJDK-11 ..."
    sudo apt-get install -y openjdk-11-jdk openjdk-11-dbg

    # Install wget
    echo "[*] Installing Wget ..."
    sudo apt-get install -y wget

    # Install Bazelisk (as bazel)
    echo "[*] Installing Bazelisk ..."
    # wget -O- https://github.com/bazelbuild/bazelisk/releases/download/v1.12.2/bazelisk-linux-amd64 \
    #     | sudo tee /usr/local/bin/bazelisk > /dev/null
    wget -O- https://github.com/bazelbuild/bazelisk/releases/download/v1.25.0/bazelisk-linux-amd64 \
        | sudo tee /usr/local/bin/bazelisk > /dev/null
    sudo chmod +x /usr/local/bin/bazelisk
    sudo ln -sf /usr/local/bin/bazelisk /usr/local/bin/bazel

    echo "[✓] Linux installation completed!"
}

update_bazelrc_for_linux() {
    echo "[*] Updating Bazel configuration ..."
    echo "[*] SMT path: ${SMT_PATH}"
    echo "[*] Bazelrc file: ${BAZELRC_PATH}"

    echo "[*] Deleting and recreating .bazelrc ..."
    rm -f "${BAZELRC_PATH}"

    cat > "${BAZELRC_PATH}" <<EOF
# Automatically generated by install.sh
build --sandbox_writable_path=${SMT_PATH}/ \\
      --action_env=SMT_DIRECTORY_PREFIX=${SMT_PATH}/ \\
      --explicit_java_test_deps
EOF

    echo "[✓] .bazelrc updated successfully!"
}

case "$OS" in
    "Linux")
        install_for_linux
        update_bazelrc_for_linux
        ;;
    "Darwin")
        echo "Unsupported system: ${OS}"
        exit 1
        ;;
    *)
        echo "Unsupported system: ${OS}"
        exit 1
        ;;
esac

echo "🎉 All done!"
