package(default_visibility = ["//visibility:public"])

filegroup(
    name = "example",
    srcs = glob(["example/**"]),
)

filegroup(
    name = "iptables-firewall",
    srcs = glob(["iptables-firewall/**"]),
)

filegroup(
    name = "hybrid-cloud-aws",
    srcs = glob(["hybrid-cloud-aws/**"]),
)

filegroup(
    name = "userstudy_network",
    srcs = glob(["userstudy_network/**"]),
)

filegroup(
    name = "userstudy_network_accessment",
    srcs = glob(["userstudy_network_accessment/**"]),
)

filegroup(
    name = "all",
    srcs = glob(["**"]),
)
